      version: '3.8'

      services:
        db:
          image: postgres:13
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
            - "5432:5432"
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

        backend:
          build: ./backend
          ports:
            - "8080:8080"
          depends_on:
            db:
              condition: service_healthy
          

        frontend:
          build: ./frontend
          ports:
            - "3000:3000"
          depends_on:
            - backend

        pinger:
          build: ./pinger
          depends_on:
            - backend

      volumes:
        postgres_data: